/*
Auto-generated by: https:///  //
Command: npx gltfjsx@6.5.3 public/models/countdown_clock.glb -o src/components/ui/ClockModel.tsx -t 
Author: danielyosefabdu (https:///  //
License: CC-BY-NC-4.0 (http:///  //
Source: https:///  //
Title: Countdown Clock - The Swan Hatch
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane018_Baked_Plane018_Baked001_0: THREE.Mesh
  }
  materials: {
    ['Plane.018_Baked.001']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function ClockModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/countdown_clock.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Plane018_Baked_Plane018_Baked001_0.geometry} material={materials['Plane.018_Baked.001']} position={[-0.889, -1.754, 12.374]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/countdown_clock.glb')
